# Generated by Django 3.2.4 on 2021-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sale',
            field=models.FloatField(default=0.0),
        ),
    ]
